PPO:
  policy: "MultiInputPolicy"
  learning_rate: 0.0005
  gamma: 0.96
  gae_lambda: 0.9 # γ
  n_steps: 50 # The number of steps to run for each environment per update
  batch_size: 50 # = n_steps * n_envs(=1)
  ent_coef: 0.1 # β
  clip_range: 0.1 # epsilon
  n_timesteps: 5_000_000