DQN:
  learning_rate: 0.00063
  buffer_size: 10_000
  batch_size: 128
  learning_starts: 0
  gamma: 0.5
  target_update_interval: 200
  train_freq: 4
  gradient_steps: -1
  exploration_fraction: 0.75
  exploration_final_eps: 0.0
  n_timesteps: 2_500_000
  policy: "MultiInputPolicy"
