DQN:
  learning_rate: 0.0005
  buffer_size: 10_000
  batch_size: 128
  learning_starts: 0
  gamma: 0.85
  target_update_interval: 200
  train_freq: 50
  gradient_steps: 2 
  exploration_fraction: 0.67
  exploration_final_eps: 0.0
  n_timesteps: 3_000_000
  policy: "MultiInputPolicy"
