DQN:
  learning_rate: 0.0005
  buffer_size: 20_000
  batch_size: 1024
  learning_starts: 0
  gamma: 0.85
  target_update_interval: 1024
  train_freq: 256
  gradient_steps: 2 
  exploration_fraction: 0.8
  exploration_final_eps: 0.0
  n_timesteps: 8_000_000 
  policy: "MultiInputPolicy"
