MountainCarContinuous-v0:
  n_timesteps: 300000
  policy: 'MlpPolicy'
  noise_type: 'ornstein-uhlenbeck' 
  noise_std: 0.5
  gradient_steps: 1
  train_freq: 1
  learning_rate: 0.001 # ambas redes actor/critic tienen el mismo lr
  batch_size: 256
  policy_kwargs: 
    net_arch: [400, 300]
  # buffer_size, tau (soft update coef), gamma

  # noise_std y noise_type se meten como parametros en la clase ActionNoise, 
  # que es lo que el modelo recibe por parametro